name: Snake Game CI

on:
  push:
    branches:
      - main   # Trigger on push to the main branch
  pull_request:
    branches:
      - main   # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ${{ matrix.os }}  # This will run on each operating system in the matrix

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Define the OS matrix

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Use your Python version here

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Assuming you have a requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover  # Adjust according to your test framework (unittest, pytest, etc.)

      - name: Run Snake Game (Example)
        run: |
          python snake_game.py  # Replace this with the actual entry point of your game
