name: Snake Game CI

on:
  push:
    branches:
      - main   # Trigger on push to the main branch
  pull_request:
    branches:
      - main   # Trigger on pull requests to the main branch

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Run on all platforms (Ubuntu, Windows, macOS)

    runs-on: ${{ matrix.os }}  # This will run the job on each operating system in the matrix

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Set your desired Python version (3.8 for example)

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install Python dependencies from requirements.txt

      - name: Run Snake Game
        run: |
          python snake_game.py  # Replace with the file that runs your Snake game (make sure it's the correct file)

